### PR TITLE
Add Icons and Placeholders.

### PR DESCRIPTION
**Pull request by mathewjordan**
## What does this do?

This pull requests introduces new componentry for `<Placeholder />` and `<Icon />`. 

### `<Placeholder />`
Placeholders are components that extend to the bounds of there container and center their children horizontally and vertically.

### `<Icon />`
Icons are sourced from the [Ionicons Filled](https://ionic.io/ionicons)  library and will be controlled a la carte. An `<Icon/>` component is essentially a tool to construct an accessible and styled `<svg>` and insert it within other components or be used on its own. An optional title can be rendered within component if the Icon is used without a corresponding label. This PR initiates the component with four available sub components rendering `<path>` elements for **Add**, **Audio**, **Image**, and **Video**. Icons currently come in three sizes corresponding the default `rem` scale of the HTML document. These can be rendered via dot notation within an <icon/>, ex: 

```
<Icon isLarge>
  <Icon.Title>Audio Work</Icon.Title>
  <Icon.Audio />
</Icon>
```

- Init SVG placeholder component.
- Init Icons and integrate w/ Placeholders.
- Add baseline docs for Placeholder/Icon.
- Update ordering, cleanup general docs.
- Add type definitions, cleanup styling structure.
- Refine types.

### CODE REVIEW

**Comment by mathewjordan** [comment]
@adamjarling This is ready for your review. Also, not seeing the Connect Issue zenhub stuff. is there a way I can set this up or do we need to involve @davidschober ?

**Comment by mathewjordan** [comment]
> @adamjarling This is ready for your review. Also, not seeing the Connect Issue zenhub stuff. is there a way I can set this up or do we need to involve @davidschober ?

Ignore my issue. Somehow my ZenHub was disconnected. Seems fine now...

**Comment by adamjarling** [comment]
Yea, Zenhub has been having issues I think.

**Review by adamjarling — APPROVED** [review]
Looks great.

**Pull request merged**
